version: '2'
services:
  node1:
    image: neo4j:3.2-enterprise
    volumes:
      - node1volume:/data
    networks:
      - node1network
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
      # - NEO4J_dbms_memory_pagecache_size=2G
      # - NEO4J_dbms_memory_heap_max__size=2G
volumes:
  node1volume:
networks:
  node1network:
